S ::= (0,0) ; U | (0,0) ; D | (0,0) ; T
U ::= (0,0) ; V | (0,0) ; V,U
D ::= (0,0) ; V;V | (0,0) ; V,D;V,
T ::= (0,0) ; V;V;V | (0,0) ; V,T;V,;V,
V ::= (0,0) ; a | (0,0) ; b | (0,0) ; c | (0,0) ; d | (0,0) ; e | (0,0) ; f | (0,0) ; g | (0,0) ; h | (0,0) ; i