<mapper> ::= <n> <lg>
<n> ::= <const_n> | <var_n> | <fun_n_g> ( <g> ) | <fun_n_n,n> ( <n> , <n> ) | <fun_n_ln> ( <ln> ) | <fun_n_ln,n> ( <ln> , <n> ) | <fun_n_lg> ( <lg> )
<ln> ::= <var_ln> | <fun_ln_n> ( <n> ) | <fun_ln_n,n> ( <n> , <n> ) | apply ( <fun_n_g> , <lg> )
<g> ::= <var_g> | <fun_g_g,n> ( <g> , <n> ) | <fun_g_lg,n> ( <lg> , <n> )
<lg> ::= <fun_lg_g,n> ( <g> , <n> ) | <fun_lg_g,ln> ( <g> , <ln> ) | apply ( <fun_g_g,n> , <ln> , <g> )
<const_n> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<var_n> ::= depth | g_count_r | g_count_rw
<var_g> ::= g
<var_ln> ::= ln
<fun_n_g> ::= size | weight | weight_r | int
<fun_n_n,n> ::= + | - | * | / | %
<fun_n_ln> ::= length | max_index | min_index
<fun_n_ln,n> ::= get
<fun_n_lg> ::= length
<fun_ln_n> ::= seq
<fun_ln_n,n> ::= repeat
<fun_g_g,n> ::= rotate_sx | rotate_dx | substring
<fun_g_lg,n> ::= get
<fun_lg_g,n> ::= split | repeat
<fun_lg_g,ln> ::= split_w